name: "GitHub Maven repo Publish Action"
description: "Build Java project with Gradle, extract metadata, and publish artifacts to GitHub repository."
inputs:
  gh_pat:
    description: "Personal Access Token for GitHub Maven artifact repository"
    required: true
  artifact_repo:
    description: "GitHub repository to publish artifacts"
    required: true
  gradle_file_path:
    description: "Path to the Gradle file"
    required: true
    default: "./gradlew"
  java_version:
    description: "Java version to set up"
    required: true
  distribution:
    description: "Java description to set up"
    required: true
  gradle_modules:
    description: "Comma-separated list of Gradle modules (e.g. ':app,:mylib'). Empty means root module."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java_version }}
    
    - name: Extract latest commit message and hash
      run: |
        GIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        GIT_HASH=$(git log --pretty=format:'%h' -n 1)
        echo "GIT_MESSAGE=$GIT_MESSAGE" >> $GITHUB_ENV
        echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
      shell: bash

    - name: Install xmlstarlet and tree
      run: sudo apt-get install -y xmlstarlet tree
      shell: bash

    - name: Build with Gradle
      run: |
        IFS=',' read -ra MODULES <<< "${{ inputs.gradle_modules }}"
        GRADLE_PATH="${{ inputs.gradle_file_path }}"

        if [ ${#MODULES[@]} -eq 0 ] || [ -z "${MODULES[0]}" ]; then
          echo "No specific modules provided. Building root project..."
          bash "$GRADLE_PATH" build
          bash "$GRADLE_PATH" publishToMavenLocal
        else
          for module in "${MODULES[@]}"; do
            echo "Building module: $module"
            bash "$GRADLE_PATH" "${module}:build"
            bash "$GRADLE_PATH" "${module}:publishToMavenLocal"
          done
        fi
      shell: bash

    - name: Checkout artifact repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.artifact_repo }}
        token: ${{ inputs.gh_pat }}
        path: artifacts

    - name: Process all generated POM files and copy artifacts
      run: |
        echo "Copying all Maven repository content to artifacts folder..."
        cp -r ~/.m2/repository/* artifacts/ 2>/dev/null || true
        # Find all POM files and process each one sequentially
        find ~/.m2/repository -type f -name "*.pom" | while read xml_file; do
          echo "Processing POM file: $xml_file"
          
          # Extract metadata from POM file
          VERSION=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:version" "$xml_file")
          GROUPID=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:groupId" "$xml_file" | sed 's/\./\//g')
          ARTIFACTID=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:artifactId" "$xml_file")
          
          echo "Processing artifact: $GROUPID/$ARTIFACTID:$VERSION"
          
          # Create directory structure in artifacts folder
          mkdir -p "artifacts/$GROUPID/$ARTIFACTID/$VERSION"
          
          # Copy entire module structure from .m2 to artifacts folder
          FIRST_TERM=$(echo "$GROUPID" | cut -d'/' -f1)
          if [ -d "~/.m2/repository/$FIRST_TERM" ]; then
            cp -r "~/.m2/repository/$FIRST_TERM"/* artifacts/ 2>/dev/null || true
          fi
          
          # Rename maven-metadata-local.xml to maven-metadata.xml if it exists
          if [ -f "artifacts/$GROUPID/$ARTIFACTID/maven-metadata-local.xml" ]; then
            mv "artifacts/$GROUPID/$ARTIFACTID/maven-metadata-local.xml" "artifacts/$GROUPID/$ARTIFACTID/maven-metadata.xml"
          fi
          
          # Define the base path for artifact files in artifacts folder
          ARTIFACT_BASE="artifacts/$GROUPID/$ARTIFACTID/$VERSION/${ARTIFACTID}-${VERSION}"
          
          # Handle JAR file (if exists)
          if [ -f "${ARTIFACT_BASE}.jar" ]; then
            echo "Generating checksums for JAR file: ${ARTIFACT_BASE}.jar"
            sha1sum "${ARTIFACT_BASE}.jar" > "${ARTIFACT_BASE}.jar.sha1"
            md5sum "${ARTIFACT_BASE}.jar" > "${ARTIFACT_BASE}.jar.md5"
          fi
          
          # Handle AAR file (if exists)
          if [ -f "${ARTIFACT_BASE}.aar" ]; then
            echo "Generating checksums for AAR file: ${ARTIFACT_BASE}.aar"
            sha1sum "${ARTIFACT_BASE}.aar" > "${ARTIFACT_BASE}.aar.sha1"
            md5sum "${ARTIFACT_BASE}.aar" > "${ARTIFACT_BASE}.aar.md5"
          fi
          
          # Handle POM file (should always exist)
          if [ -f "${ARTIFACT_BASE}.pom" ]; then
            echo "Generating checksums for POM file: ${ARTIFACT_BASE}.pom"
            sha1sum "${ARTIFACT_BASE}.pom" > "${ARTIFACT_BASE}.pom.sha1"
            md5sum "${ARTIFACT_BASE}.pom" > "${ARTIFACT_BASE}.pom.md5"
          fi
          # Display the final directory structure
          tree -s artifacts/$GROUPID/$ARTIFACTID/$VERSION
          echo "Completed processing artifact: $GROUPID/$ARTIFACTID:$VERSION"
        done
      shell: bash

    - name: Commit and push files
      run: |
        cd artifacts
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "${{ env.GIT_MESSAGE }} https://github.com/${{ github.event.repository.full_name }}/commit/${{ env.GIT_HASH }}. Version: ${{ env.VERSION }}"
      shell: bash
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.gh_pat }}
        repository: ${{ inputs.artifact_repo }}
        force_with_lease: true
        directory: artifacts
